version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spring-app
    ports:
      - "8080:8080"
    networks:
      - spring-network

networks:
  spring-network:
